export const LOAD_COURSES = 'LOAD_COURSES';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';

export const SAVE_COURSE = 'SAVE_COURSE';
export const SAVE_COURSE_SUCCESS = 'SAVE_COURSE_SUCCESS';

export const GET_COURSE = 'GET_COURSE';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';

export const UPDATE_COURSES_SUCCESS = 'UPDATE_COURSES_SUCCESS';

export const LOAD_AUTHORS = 'LOAD_AUTHORS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
